# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=True, verbose_name='subscribed')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('created_on', models.DateField(blank=True, verbose_name='created on')),
                ('updated_on', models.DateField(blank=True, verbose_name='updated on')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
