# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_join'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
