# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'This email is already registered'}, max_length=254, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('optin', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
