# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('introduction', models.TextField(verbose_name='introduction')),
                ('page_hero', models.TextField(verbose_name='page hero')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
