# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bodytext',
            field=models.TextField(verbose_name='message'),
        ),
    ]
